pub const DOCGEN_SYSTEM_PROMPT: &str = r#"You are a document generator for AuraForge, a project planning tool. Your job is to
extract information from a planning conversation and generate specific documentation.

CRITICAL RULES:
1. Only include information that was explicitly discussed or decided in the conversation
2. If a topic wasn't covered, either omit it or mark it as "[To be determined]"
3. Never invent features, technologies, or requirements that weren't discussed
4. If the conversation was incomplete, note what's missing in an "Open Questions" section
5. Be specific—use exact names, versions, and details from the conversation
6. Format output as clean, valid Markdown"#;

pub const README_PROMPT: &str = r#"Generate a README.md for this project based on the planning conversation below.

The README should:
1. Have a clear title with the project name
2. Include "Generated by AuraForge on {current_date}"
3. Explain what's in the folder and how to use the files
4. Provide a brief project overview (2-3 sentences)
5. List key decisions made during planning

Structure:
- What Is This? (1 paragraph explaining the folder contents)
- Files Included (table of files with purposes)
- How to Use (numbered steps to get started with Claude Code)
- Project Overview (summary of what's being built)
- Key Decisions (bullet list of major choices made)

Keep it concise—this is a quick-start guide, not the full spec.

<conversation>
{conversation_history}
</conversation>

Generate the README.md now:"#;

pub const SPEC_PROMPT: &str = r#"Generate a comprehensive SPEC.md based on the planning conversation below.

Extract and organize:

1. **Overview**: What is this project? Who is it for? (from early conversation)

2. **Problem Statement**: Why does this need to exist? What problem does it solve?

3. **Goals**: Explicit objectives mentioned. Be specific.
   - If user said "I want it to be fast" → "Sub-100ms response times for API calls"

4. **Non-Goals**: Things explicitly ruled out or deferred
   - "Not doing X for v1" / "Out of scope" / "Maybe later"

5. **User Stories**: Convert discussed features into user story format
   - "As a [user type], I want to [action] so that [benefit]"

6. **Technical Architecture**:
   - Tech stack with specific versions if mentioned
   - System design (create ASCII diagram if architecture was discussed)
   - Data models (entities and relationships)

7. **Features**:
   - Core features (must have for v1)
   - Future features (mentioned but deferred)
   - For each: description + acceptance criteria

8. **API Design**: Only if backend/API was discussed
   - Endpoints with methods, paths, request/response

9. **Security Considerations**: Auth, data handling, etc. if discussed

10. **Open Questions**: Anything unresolved in the conversation

If a section has no information from the conversation, include the heading with
"[Not discussed - to be determined]" rather than inventing content.

<conversation>
{conversation_history}
</conversation>

Generate the SPEC.md now:"#;

pub const CLAUDE_PROMPT: &str = r#"Generate a CLAUDE.md file for Claude Code based on the planning conversation below.

This file will be placed in the project root to give Claude Code context about the project.
It should be concise and actionable—Claude Code will reference this while building.

Include:

1. **Project Overview**: 2-3 sentences max. What is this?

2. **Tech Stack**: Bullet list of technologies with versions
   - Only include what was decided in the conversation
   - Format: "- **Category**: Technology (version if specified)"

3. **Project Structure**: ASCII tree of the folder structure
   - Base on tech stack conventions if not explicitly discussed
   - Keep it to top 2-3 levels

4. **Commands**: Standard commands for this tech stack
   - Install, dev, build, test, lint
   - Use actual package manager/commands for the chosen stack

5. **Code Conventions**:
   - Naming conventions (if discussed)
   - File organization rules
   - Any specific patterns mentioned

6. **Common Tasks**: Brief how-to for:
   - Adding a new component/module
   - Adding a new API endpoint (if applicable)
   - Running tests

7. **Important Notes**: Project-specific gotchas or rules mentioned

Keep each section brief. Claude Code needs quick reference, not exhaustive documentation.

<conversation>
{conversation_history}
</conversation>

Generate the CLAUDE.md now:"#;

pub const PROMPTS_PROMPT: &str = r#"Generate a PROMPTS.md implementation guide based on the planning conversation below.

This file contains step-by-step prompts that the user will paste into Claude Code.
Each phase should be a self-contained unit of work with clear verification steps.

CRITICAL: The prompts must be copy-pasteable. Write them as if speaking directly to Claude Code.

Structure each phase:

## Phase N: [Name]

### Prompt
```
[The exact prompt to paste into Claude Code]

[Clear, specific instructions]
[Reference CLAUDE.md for conventions]
[List specific outcomes expected]
```

### What You Should Have After
- [ ] [Verifiable checklist item]
- [ ] [Another checklist item]

### Verification Command
```bash
[Command to verify this phase worked]
```

### Common Issues
- If [problem], try [solution]

---

Guidelines for creating phases:

1. **Phase 1 is always Project Setup**: Initialize, install dependencies, verify "hello world"

2. **Order by dependency**: Build foundation before features that depend on it

3. **Each phase = testable milestone**: User should be able to verify before continuing

4. **Prompts should be specific**:
   - BAD: "Add user authentication"
   - GOOD: "Add user authentication using NextAuth.js with GitHub and email providers.
     Create a login page at /login, protect the /dashboard route, and add a user
     dropdown in the header showing the logged-in user's name."

5. **Include file paths**: Tell Claude Code where to create files

6. **Reference other docs**: "See SPEC.md for the data model" / "Follow CLAUDE.md conventions"

7. **Final phase is always Polish**: Error handling, edge cases, cleanup

Based on the conversation, identify the natural phases. Usually:
- Setup (always first)
- Core data/models (if database)
- Core feature 1
- Core feature 2
- ...
- Integration/connecting features
- Polish (always last)

<conversation>
{conversation_history}
</conversation>

Generate the PROMPTS.md now:"#;
